### ISSUE TITLE
How it's suppose to look like?

### ISSUE THREAD

**Issue by 3vilguy** [vitalyliber/react-native-ckeditor#1]
Hi there, I'm currently investigating some WYSIWYG editors for RN and I came across your project.
I've installed your lib, but all I see is an input field.

![Screenshot 2019-08-09 at 01 39 32](https://user-images.githubusercontent.com/2122619/62746280-acbc2800-ba46-11e9-83f0-6b062dc2ca78.png)

Is that it? Or am I missing something?

**Comment by vitalyliber** [comment]
@3vilguy  I'm sorry. I can't support it anymore.
I refuse from this package in my projects. Because this is very difficult to support it.
Now I use skeditor only for web.

**Comment by 3vilguy** [comment]
Shame since it looked like exactly what I was looking for :(
Thanks for letting me know and GL with other projects :)
