### ISSUE TITLE
No ckeditor panel opened

### ISSUE THREAD

**Issue by Androbhikk73** [vitalyliber/react-native-ckeditor#5]
i have used the latest version, here i am attaching my code,

<CKEditor
      content={this.state.about}
      onChange={value => {
            setFieldValue('about', value);
     }}
 />

but no panel is opened, can anyone help me out?

**Comment by Saidfatah** [comment]
the same problem its hsows some html but the editor is not editable

**Comment by rajneshbiz** [comment]
the same issue even in my case showing nothing on the page and terminal a message is coming
WebViewEditor: sending message .......


here is the complete code.

		import CKEditor from 'react-native-ckeditor'
		const App = () => {
		  const [description, setdescription] = useState(`<p>The <code class=" language-php">firstOrNew</code> method, like <code class=" language-php">firstOrCreate</code> will attempt to locate a record in the database matching the given attributes. However, if a model is not found, a new model instance will be returned. Note that the model returned by <code class=" language-php">firstOrNew</code> has not yet been persisted to the database. You will need to call <code class=" language-php">save</code> manually to persist it:</p>`);
		  const setFieldValue = (value) => {
		    console.log(value);
		  }
		  return (
		    <>
		      <StatusBar barStyle="dark-content" />
		      <SafeAreaView>
		        <ScrollView
		          contentInsetAdjustmentBehavior="automatic"
		          style={styles.scrollView}>
		          <View style={styles.body}>
		           
		            <View style={styles.sectionContainer}>
		              <CKEditor
		                content={description}
		                onChange={value => {
		                  setFieldValue(value);
		                }}
		                style={{flex:1}}
		              />
		            </View>
		          </View>
		        </ScrollView>
		      </SafeAreaView>
		    </>
		  );
		};

**Comment by vitalyliber** [comment]
Hi. Please use this package only you want to improve it. 
I don't use it.
It is don't supported by me.
